export default {
  SIGN_UP: 'SIGN_UP',
  LOG_IN: 'LOG_IN',
  START_FETCHING: 'START_FETCHING',
  STOP_FETCHING: 'STOP_FETCHING',
  CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
  CHECK_AUTH_STATUS_FAIL: 'CHECK_AUTH_STATUS_FAIL',
};
